package com.web.money;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class NavigateMoneyTestTest 
{
	
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void navigateMoneyTest() {
    driver.get("http://localhost:8080/MoneyWeb/argentContent");
    driver.manage().window().setSize(new Dimension(1371, 744));
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.id("amount01")).click();
    driver.findElement(By.id("amount01")).sendKeys("150");
    driver.findElement(By.id("amount02")).click();
    driver.findElement(By.id("amount02")).sendKeys("40000");
    driver.findElement(By.id("currency02")).click();
    {
      WebElement dropdown = driver.findElement(By.id("currency02"));
      dropdown.findElement(By.xpath("//option[. = 'GBP']")).click();
    }
    driver.findElement(By.cssSelector("#currency02 > option:nth-child(3)")).click();
    driver.findElement(By.id("currency01")).click();
    {
      WebElement dropdown = driver.findElement(By.id("currency01"));
      dropdown.findElement(By.xpath("//option[. = 'USD']")).click();
    }
    driver.findElement(By.cssSelector("#currency01 > option:nth-child(2)")).click();
    driver.findElement(By.cssSelector("input:nth-child(3)")).click();
    driver.findElement(By.id("amount01")).click();
    driver.findElement(By.id("amount01")).sendKeys("300");
    driver.findElement(By.id("currency01")).click();
    {
      WebElement dropdown = driver.findElement(By.id("currency01"));
      dropdown.findElement(By.xpath("//option[. = 'CHF']")).click();
    }
    driver.findElement(By.cssSelector("#currency01 > option:nth-child(4)")).click();
    driver.findElement(By.id("amount02")).click();
    driver.findElement(By.id("amount02")).sendKeys("160000");
    driver.findElement(By.id("currency02")).click();
    driver.findElement(By.cssSelector("#currency02 > option:nth-child(1)")).click();
    driver.findElement(By.cssSelector("input:nth-child(3)")).click();
  }

}
